// 简历 / 作品集数据 — 来源：杨运栋 简历（2028 届 · AI 应用开发实习）+ 5 个 GitHub 开源项目
// 口径与简历逐项对齐：5 个项目 = 163 + 908 + 71 + 79 + 50 = 1271 条测试
// 5 个项目各设一个"最强记忆点"，避免同质化

export const profile = {
  name: '杨运栋',
  nickname: '栋',
  github: 'Dongnb66',
  email: '2088417049@qq.com',
  school: '吉首大学 · 张家界学院',
  major: '计算机科学与技术',
  grade: '2024 级 · 大三',
  goal: 'AI Agent 后端开发工程师 · 多智能体 / RAG / LLM 应用工程',
  intro: [
    '吉首大学张家界学院 <span class="tag">2024 级</span> 计算机科学与技术专业在读，大三。',
    '求职方向 <strong>AI Agent 后端开发</strong>。已独立完成 5 个端到端项目，全部 <span class="tag">MIT License</span> 开源在 GitHub（早期软件杯 A3 参赛原型已重写演进并入主项目）。',
    '测试基线：<strong>5 个项目共 1271 条单测/冒烟断言</strong>（零 API Key 可跑）+ <strong>9 条防幻觉评测用例（6 常规 + 3 对抗）</strong>，常规集挂入 GitHub Actions CI。',
    'AI Coding 工作流：以 <strong>Claude Code、Codex、WorkBuddy</strong> 等 AI 智能体编程工具深度协作开发——需求拆解 → 生成 → 人工审校 → 测试验证，<strong>设计决策与代码验收由本人把关</strong>。其中一次真实实验（检索层误拒 25/36（69.4%）的失败证明与修复）已写成公开技术文章发布在掘金。',
    '对多智能体编排、RAG 防幻觉、LLM 调用工程有完整实战经验。<strong>日常实习可立即到岗</strong>，同时准备 2027 年 3–5 月暑期实习窗口，期望找到能独立交付模块的 AI Agent 实习岗位。',
  ],
};

export const stats = [
  { num: '5', label: 'GitHub Projects', sub: '2026.09 开源 · 全 MIT' },
  { num: '8', label: 'Node 状态图', sub: '5 LLM 智能体 + 2 记忆 + 1 ReAct' },
  { num: '1271', label: 'Tests', sub: '5 项目 · 零 Key 可跑 · CI 持续通过' },
  { num: '2027', label: '暑期实习窗口', sub: '日常实习亦可 · 可立即到岗' },
];

// 5 个项目差异化：每个项目一个"最强记忆点"
export const projects = [
  {
    id: 'python-learning-agent',
    name: 'python-learning-agent',
    sub: 'BACKEND · AGENT ENGINEERING',
    memory: '主推 · 求职主项目 · 后端工程化',
    desc: '基于 LangGraph 的多智能体学习助手：8 节点状态图编排 5 个 LLM 智能体 + 2 个记忆节点 + 1 个 ReAct 自主辅导 Agent，完成"记忆读取—诊断—规划—出题—资源—复盘—自主辅导—记忆沉淀"全流程；配 <strong>React 用户端 9 页面</strong>（画像对话 / 资源生成 / 学习路径 / 智能辅导 / 前后测实证等），<strong>前后端一体、面试可完整演示</strong>。',
    tags: ['Python', 'LangGraph', 'FastAPI', 'RAG', 'React', 'DeepSeek', 'JWT', 'TC3-HMAC', '三层记忆'],
    badges: ['主推 · 求职主项目', '后端工程化'],
    highlights: [
      'LangGraph 8 节点 + 条件边：load_memory → … → review →(有薄弱项) tutor → save_memory',
      '三层记忆：短期上下文 AgentState / 长期画像 profiles 表 / 学情轨迹 learning_sessions 表',
      '自实现腾讯云短信 TC3-HMAC-SHA256 签名，<strong>零 SDK 依赖</strong>',
      'ReAct 自主辅导 Agent：模型自主决定调哪个工具、调几轮、何时停，逐轮留可审计 trace',
      '<strong>React 用户端 9 页面</strong> + /api 兼容层 21 端点，Gradio / Swagger / React 三种演示入口',
      '<strong>防幻觉三道代码级约束</strong>：检索零分即空（无命中不硬凑）/ 检索为空直接拒答且不调模型 / URL 白名单剔除库外链接',
      '<strong>防幻觉评测集</strong>：零配置可跑（9 用例 = 6 常规 + 3 对抗 / 4 类断言 / JSON 报告），常规集挂 CI，实测编造链接 0 条',
      '<strong>检索层离线基准</strong>：在 <strong>12 篇小语料</strong>上自建 60 条标注查询 + 固定种子随机基线（<strong>绝对值不可外推</strong>），实测默认路径 Hit@1 19.4%、误拒 25/36 = 69.4%；用<strong>同分冲突</strong>证明<strong>任何只依赖词法分数的判据，对这一对输入必然错一个</strong>（IDF 覆盖率、稀有词计数实测同样分不开）→ 修复分两层：<strong>CJK bigram 分词从「只在混合路生效」改到默认词法路</strong>（同分母 Hit@1 19.4% → 77.8%、误拒 25 条 → 2 条）+ <strong>相关性阈值 2.0</strong>（零召回代价把语料外误放行压到 1/22）；<strong>Embedding 双路 + RRF + 两路名次一致性放行</strong>作为可选增强；<strong>代价在拒答侧：语料外 22/22 → 21/22、争议组 2/2 → 0/2</strong>。未配 Key 自动降级、失败不重试',
      '<strong>技术文章（掘金首发）</strong>：把上面这次检索基准的失败与修复写成完整复盘——含阈值敏感性、检索延迟、每条漏网查询漏在哪一层 → <a href="https://juejin.cn/post/7689091429971902499" target="_blank" rel="noopener noreferrer">juejin.cn/post/7689091429971902499</a>',
      '完整 Dockerfile + docker-compose + pytest 163 passed + .env.example',
    ],
    github: 'https://github.com/Dongnb66/python-learning-agent',
    demo: 'README + Dockerfile + docker-compose，clone 即跑',
    cover: 'python',
    feature: true,
  },
  {
    id: 'campus-mutual-aid',
    name: 'campus-mutual-aid',
    sub: 'MULTI-AGENT · PIPELINE · SPA',
    memory: '多智能体工程化 · 流水线',
    desc: '校园互助平台：多智能体流水线处理求助 / 资源 / 失物招领，配合作风评分机制。<strong>最大亮点是多智能体的"工程化"落地</strong>——智能路由、评分反馈、抗滥用，不是 demo 而是能跑。',
    tags: ['Node.js', 'Express', 'node:sqlite', 'MySQL', 'Redis', '多智能体', 'SMTP', 'TC3 签名', 'React 18'],
    badges: ['多智能体工程化'],
    highlights: [
      '5 智能体流水线：路由 Router / 发帖引导 PostGuide / 内容审核 Audit / 检索 Search / 撮合 Match',
      '完整账号体系：手机/邮箱/微信/QQ，<strong>首次扫码强校验</strong>',
      '<strong>React 18 + Vite 5 前端</strong>，JWT 双令牌 + RBAC、事务防并发、自实现 TTL+LRU 缓存',
      '服务端共 <strong>71 项测试</strong>（48 行为断言 + 10 冒烟 + 13 缓存）：行为测试用 fetch 桩把模型换成可控脚本，断言"无 Key 时 0 次请求""模型 500 时违规拦截依然生效"',
      '<strong>测试查出 2 个真 bug 并修复</strong>：seed 脚本的 process.exit 会杀掉启动中的服务、.env 里的 Key 永远读不到（ESM import 提升导致）',
      'Node 单一 runtime，部署 / 学习 / 二次开发都简单',
    ],
    github: 'https://github.com/Dongnb66/campus-mutual-aid',
    demo: 'clone 后 npm i && node server.js 即跑',
    cover: 'campus',
  },
  {
    id: 'mcp-toolkit',
    name: 'mcp-toolkit',
    sub: 'MCP PROTOCOL · TYPESCRIPT · STDIO',
    memory: 'MCP 协议工程 · 工具资产复用 · 50 单测',
    desc: '把散落各项目的手写工具能力，标准化为 8 个即插即用的 MCP 工具服务器。<strong>从 function calling 到 MCP 协议</strong>：travel-rank 的聚合排名、python 项目的 TC3 签名器直接复用为零重构的标准工具。',
    tags: ['TypeScript', 'MCP 协议', 'JSON-RPC', 'zod', 'stdio', '50 单测'],
    badges: ['MCP 协议工程', '工具资产复用', '50 单测'],
    highlights: [
      '官方 MCP SDK + TypeScript：<strong>McpServer + StdioServerTransport（JSON-RPC over stdio）</strong>，任意宿主即插即用',
      '8 工具：热度聚合排名 / TC3 签名 / 只读 SQLite / 网页抽取 / 文本切块 / 日期计算 / JWT 验签 / 探活',
      '<strong>lib/tools 分层铁律</strong>：lib 层纯函数零 MCP 依赖，tools 层只做 zod 校验 + 转发',
      '只读 SQLite 工具做<strong>三重约束</strong>：只允许 SELECT/WITH/PRAGMA + readOnly 打开 + 可读路径限定在 <code>MCP_SQLITE_ROOT</code> 根目录内',
      '<strong>50 个 vitest 单测全绿</strong> + GitHub Actions CI（typecheck + build + test）',
    ],
    github: 'https://github.com/Dongnb66/mcp-toolkit',
    demo: 'npm i && npm run dev，接 MCP Inspector 即跑',
    cover: 'mcp',
  },
  {
    id: 'travel-rank',
    name: 'travel-rank · 途见',
    sub: 'REACT AGENT · TOOL CALLING · 真实截图',
    memory: 'ReAct 自主决策 · 真实截图',
    desc: '旅游口碑聚合 + AI 对话式推荐。<strong>最大亮点是 ReAct 式自主决策 Agent</strong>——模型通过 <strong>tool_choice:auto</strong> 自己决定调不调工具、调哪个、够不够、要不要再来一轮（无 tool_calls 即自终止，4 轮上限防失控），可选工具含百度地图搜宝藏地点；口碑榜配桌宠猪猪形象交互。<strong>本作品集唯一有真实运行截图的项目</strong>。',
    tags: ['Express', 'ReAct Agent', '百度地图 API', 'TC3 签名', 'SMTP', '原生 SPA'],
    badges: ['真实运行截图', 'ReAct 自主决策'],
    highlights: [
      '<strong>ReAct 自主决策循环</strong>：<strong>36 项 ReAct 决策断言</strong>（项目测试合计 79 项 = 36 断言 + 30 冒烟 + 13 TC3 签名向量）用 fetch 桩把模型换成可控脚本，逐条验证「决策权真交给模型」「工具结果回灌真实库数据」「模型说停才停」「连续要工具时钉死 4 轮」',
      '<strong>Function Calling</strong> 实战：AI 主动调百度地图查景点 / 路线 / 宝藏地点',
      '多源口碑聚合 + 权重排序算法',
      '<strong>桌宠猪猪 + 私信通知 + 个人中心抽屉</strong>',
      '<strong>真实运行截图 4 张</strong>：登录 / 口碑榜 / 桌宠对话 / 个人中心',
    ],
    github: 'https://github.com/Dongnb66/travel-rank',
    demo: '本作品集 Hero 区有 4 张真实运行截图',
    cover: 'travel',
  },
  {
    id: 'internship-workbench',
    name: 'internship-workbench',
    sub: 'MULTI-TENANT · RLS · 4 CLIENTS',
    memory: '多租户隔离靠数据库不靠自觉 · 四端共用一套口径',
    desc: '求职全流程平台：岗位广场 → 投递台账 → 面试备战，Web / 微信小程序 / Chrome 扩展 / 本地抓取器四端共用一套数据与口径。<strong>最大亮点是把多租户隔离下沉到数据库</strong>——RLS 行级策略强制归属，不依赖应用层自觉；这套隔离本身也被写成了断言。',
    tags: ['React 19', 'TypeScript', 'PostgreSQL', 'RLS', 'Chrome MV3', '微信小程序', 'Playwright', '契约测试', 'Docker'],
    badges: ['多租户架构', '四端复用', '908 项测试', '线上运行 · 有真实访问'],
    highlights: [
      '<strong>真实使用</strong>：<strong>约 27 台真实浏览器</strong>访问、<strong>2 台连上助手</strong>（含少量验证身份，非精确真人计数），<strong>1 台跑通「装本地助手 → 抓取 → 入库」全链路</strong>；据真机反馈修掉 4 个只有真机会暴露的缺陷',
      '<strong>Windows 本地助手</strong>：零依赖安装包（双击即装、开机自启、带停止与卸载）；Playwright 内核 · <strong>27 个站点接入 / 7 个实测可用</strong>（三态标注）· 串行 + 随机抖动 + 页数上限；只读公开页面、命中风控即停不绕',
      '<strong>匿名计数与漏斗埋点</strong>：尊重 GPC；<strong>匿名端对两张表只能 INSERT、无任何 SELECT 权限</strong>；活跃与「装过助手」全部由事件表推导 —— 一条从未成功的 UPDATE 通道被整条删掉，而不是加补丁',
      '<strong>多租户隔离靠数据库不靠自觉</strong>：10 张私有表全部 <code>USING</code> + <code>WITH CHECK</code> 双写 RLS 策略——少了 WITH CHECK，UPDATE 就能把行改成别人的 <code>owner_id</code>，等于越权后门；归属列 <code>DEFAULT auth.uid()</code> 由库生成，客户端无从指定。前端不传 owner_id、写操作空返回即抛错，<strong>三条防线全写成断言</strong>',
      '<strong>把 PostgREST 的静默语义翻译成显式错误</strong>：RLS 拒绝写入时它返回的是空数组而不是报错，不翻译的话用户看到「保存成功」而数据根本没落库；insert / update / delete 三条写路径各自识别并抛错',
      '<strong>一套口径四端复用</strong>：Web 与微信小程序共用同一批表与同一套 RLS 约定；Chrome 扩展（<code>activeTab</code> + 零 <code>host_permissions</code>）只读当前页 DOM，<strong>全目录 0 次网络请求、数据不出本机</strong>；本地抓取器串行 + 随机抖动（2600–3640ms）+ 页数上限，只读公开接口、命中风控即停不绕',
      '<strong>契约测试钉住跨端一致性</strong>：Web（TS/ESM）与小程序（CommonJS）无法共享代码，改为真实加载两端后逐项比对渠道表 / 岗位类型 / 日期函数 / 去重键。这类错位的症状是「导入成功但字段全空」——<strong>不报错，所以必须断言</strong>',
      '<strong>提取算法只写一份</strong>：扩展与抓取器共用同一份 <code>collector.js</code>；测试从源码推导扩展侧字段键，再断言抓取器是其超集且多出的字段必须有理由——防「两边一起改名一起错」',
      '<strong>CI 把工具看不见的失败变成断言</strong>：lint / typecheck / test / build 四道门，并用<strong>两个时区各跑一遍测试</strong>（UTC+8 会把「Web↔小程序 daysLeft 差一天」抵消成假绿）',
    ],
    github: 'https://github.com/Dongnb66/internship-workbench',
    demo: 'clone 后 npm i && npm test（离线可跑）；端到端需自配云后端',
    cover: 'workbench',
  },
];

// 技能地图：按"做了哪些事"分类，每个领域都有真实项目背书
export const skills = [
  {
    icon: '🧠',
    name: '多智能体编排',
    desc: '规划智能体调度子智能体协同，而非单一 prompt 硬编流程',
    list: ['LangGraph', 'langchain-core（Tool 定义）', 'planner/profile/quiz/review', '状态机'],
  },
  {
    icon: '🔍',
    name: 'RAG 防幻觉',
    desc: '检索增强生成 + 引用溯源，让回答可查证、可回落',
    list: ['RAG', 'BM25 稀疏检索', '混合检索 + RRF 融合', '相关性阈值拒答'],
  },
  {
    icon: '☕',
    name: 'Java / Spring Boot 后端',
    desc: 'Spring Boot 3 + Java 21 智能体平台后端项目实证，core 层纯 Java 可独立测试',
    list: ['Spring Boot 3', 'Java 21', 'JPA(H2/MySQL)', 'JUnit', 'REST API'],
  },
  {
    icon: '🛡️',
    name: '账号 / 鉴权体系',
    desc: '从零实现完整账号闭环：注册到第三方扫码，安全可审计',
    list: ['JWT', 'bcrypt', '微信/QQ OAuth', '手机/邮箱验证码'],
  },
  {
    icon: '📨',
    name: '短信 / 邮件集成',
    desc: '自实现厂商签名协议，零官方 SDK 依赖，可控可测',
    list: ['腾讯云 TC3-HMAC-SHA256', 'SMTP', '验证码限流', '企业微信推送'],
  },
  {
    icon: '⚙️',
    name: '后端工程化',
    desc: 'FastAPI / Express / Spring Boot 分层，配置、中间件、错误处理齐全',
    list: ['FastAPI', 'Express', 'Spring Boot', 'SQLAlchemy', 'node:sqlite'],
  },
  {
    icon: '🧪',
    name: '测试驱动交付',
    desc: '端到端管线 + 官方签名测试向量 + 跨会话记忆，交付前可自动验证',
    list: ['pytest', 'vitest', 'node --test', 'JUnit', '防幻觉评测集', '1271 条测试与断言'],
  },
  {
    icon: '🚀',
    name: '容器化部署',
    desc: '一键 clone 即跑，降低面试官上手成本',
    list: ['Docker', 'docker-compose', '.env.example', 'README 中英双语'],
  },
  {
    icon: '⚛️',
    name: '前端（全栈互补）',
    desc: '能独立做交互前端，用原生或框架按场景取舍',
    list: ['React', 'Vite', '原生 SPA', 'CSS 动效'],
  },
  {
    icon: '🌐',
    name: 'Function Calling',
    desc: '让 AI 主动调用外部工具（地图/查询）完成任务',
    list: ['工具调用', '百度地图 API', '轮数上限收敛', '结果回填'],
  },
  {
    icon: '🧩',
    name: 'MCP 协议开发',
    desc: '把 function calling 工具标准化为 MCP 协议工具服务器，任意宿主跨项目复用',
    list: ['TypeScript', 'JSON-RPC', 'zod', 'stdio transport'],
  },
];
